<Project>
  <PropertyGroup>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <DebugType>none</DebugType>
    <DebugSymbols>false</DebugSymbols>
    <EmbedUntrackedSources>false</EmbedUntrackedSources>
    <PathMap>$([System.IO.Path]::GetFullPath('$(MSBuildThisFileDirectory)'))=/src</PathMap>
  </PropertyGroup>
</Project>
